# Generated by Django 4.0.6 on 2022-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto2',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='contato',
            name='foto3',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
